// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIE6L2YVU9dNX0Lj_WkrihAXIM_IIza34',
    appId: '1:250338435801:web:6bf8eed6575460751c54c8',
    messagingSenderId: '250338435801',
    projectId: 'insta-1841b',
    authDomain: 'insta-1841b.firebaseapp.com',
    storageBucket: 'insta-1841b.firebasestorage.app',
    measurementId: 'G-1K1JLCY8Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbOvooLqCZp5xXsYJoM1bVwDS9_R0Hv4w',
    appId: '1:250338435801:android:ddd8de8871e9db841c54c8',
    messagingSenderId: '250338435801',
    projectId: 'insta-1841b',
    storageBucket: 'insta-1841b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0zD0YzYfEY_mDgUZrOU2LXnT6Cna3NxQ',
    appId: '1:250338435801:ios:569e55d2c85a27b11c54c8',
    messagingSenderId: '250338435801',
    projectId: 'insta-1841b',
    storageBucket: 'insta-1841b.firebasestorage.app',
    iosBundleId: 'com.example.instachef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0zD0YzYfEY_mDgUZrOU2LXnT6Cna3NxQ',
    appId: '1:250338435801:ios:569e55d2c85a27b11c54c8',
    messagingSenderId: '250338435801',
    projectId: 'insta-1841b',
    storageBucket: 'insta-1841b.firebasestorage.app',
    iosBundleId: 'com.example.instachef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIE6L2YVU9dNX0Lj_WkrihAXIM_IIza34',
    appId: '1:250338435801:web:74d24918125694111c54c8',
    messagingSenderId: '250338435801',
    projectId: 'insta-1841b',
    authDomain: 'insta-1841b.firebaseapp.com',
    storageBucket: 'insta-1841b.firebasestorage.app',
    measurementId: 'G-X00S46SYJ5',
  );
}
